name: Give Me A Runner

on:
  workflow_dispatch:
    inputs:
      lifespan_minutes:
        description: Runner lifespan in minutes
        required: true
        type: number
        default: 60
      size:
        type: choice
        description: Runner size
        default: standard-2
        options:
          - standard-2
          - standard-4
          - standard-8
          - standard-16
          - standard-32
      boot_image:
        type: choice
        description: Runner boot image
        default: ubuntu-2204
        options:
          - ubuntu-2204
          - ubuntu-2004

      arch:
        type: choice
        description: Runner architecture
        default: x64
        options:
          - x64
          - arm64

jobs:
  run:
    runs-on: ubicloud-${{ inputs.size }}${{ inputs.arch == 'arm64' && '-arm' || '' }}-${{ inputs.boot_image }}

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: IPv4 Address
      run: curl -sL --ipv4 ifconfig.me

    - name: IPv6 Address
      run: curl -sL --ipv6 ifconfig.me

    - name: Hostname
      run: hostname -I

    - name: Deploy dev ssh keys
      run: |
        sudo sh -c 'echo "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBF8s1PMJQfyKMrbi408/aFNXt1Ey14NIftFOtDtm2qo4JXU0dOEA5s7D8ADlskroMXtLQyPJjePHDn1OCNE/A8c= dev+ben@ubicloud.com" >> /home/runneradmin/.ssh/authorized_keys'
        sudo sh -c 'cat /home/runneradmin/.ssh/authorized_keys'

    - name: Sleep
      run: sleep $((${{ inputs.lifespan_minutes }} * 60))
